remove old, broken non-LTS qt versions (5.14, 5.13, 5.12)
These older Qt releases are out of support, the builds are all broken, and it looks like Qt has even yanked the source downloads from their website, so you can't even get copies from the primary source. We haven't used Qt 5.14 or older for anything in a while, so there's not much value in these older-version variant formulas. I have little interest in dealing with old unsupported versions of Qt (or any Qt I don't have to, for that matter), so I'm going to just delete them and clean things up here instead of trying to find workarounds. Less files to scroll through in the repo now anyway, so this is probably a net positive

qt 5.14's archive file, at least on ftp.osuosl, appears corrupt or bad. And it's reeeeally slow to download. Breakage looks like this:

```
==> Fetching octave-app/octave-app/qt_5.14
==> Downloading https://download.qt.io/official_releases/qt/5.14/5.14.2/single/qt-everywhere-src-5.14.2.tar.xz
Already downloaded: /Users/janke/Library/Caches/Homebrew/downloads/79e4952d6a6661213a9f89064f912877f5b6e7a3fba13c9f6462e05ecb253dfe--qt-everywhere-src-5.14.2.tar.xz
==> Installing qt_5.14 from octave-app/octave-app
qt-everywhere-src-5.14.1/qtbase/tests/auto/widgets/graphicsview/qgraphicspixmapitem/tst_qgraphicspixmapitem.cpp: Lzma library error: Corrupted input data
tar: Error exit delayed from previous errors.
Error: Failure while executing; `/usr/bin/env tar --extract --no-same-owner --file /Users/janke/Library/Caches/Homebrew/downloads/79e4952d6a6661213a9f89064f912877f5b6e7a3fba13c9f6462e05ecb253dfe--qt-everywhere-src-5.14.2.tar.xz --directory /private/tmp/homebrew-unpack20240409-64987-q18ttx` exited with 1. Here's the output:
qt-everywhere-src-5.14.1/qtbase/tests/auto/widgets/graphicsview/qgraphicspixmapitem/tst_qgraphicspixmapitem.cpp: Lzma library error: Corrupted input data
tar: Error exit delayed from previous errors.
```

Or:

```
/Applications/Xcode-15.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -o "../bin/qmake" main.o meta.o option.o project.o property.o ioutils.o proitems.o qmakebuiltins.o qmakeevaluator.o qmakeglobals.o qmakeparser.o qmakevfs.o pbuilder_pbx.o makefile.o makefiledeps.o metamakefile.o projectgenerator.o unixmake2.o unixmake.o mingw_make.o msbuild_objectmodel.o msvc_nmake.o msvc_objectmodel.o msvc_vcproj.o msvc_vcxproj.o winmakefile.o xmloutput.o qutfcodec.o qendian.o qglobal.o qlogging.o qmalloc.o qnumeric.o qoperatingsystemversion.o qrandom.o qabstractfileengine.o qbuffer.o qdatastream.o qdebug.o qdir.o qdiriterator.o qfile.o qfiledevice.o qfileinfo.o qfilesystemengine.o qfilesystementry.o qfsfileengine.o qfsfileengine_iterator.o qiodevice.o qsettings.o qtemporaryfile.o qtextstream.o qjsonarray.o qjson.o qjsondocument.o qjsonobject.o qjsonparser.o qjsonvalue.o qmetatype.o qsystemerror.o qvariant.o quuid.o qarraydata.o qbitarray.o qbytearray.o qbytearraylist.o qbytearraymatcher.o qcalendar.o qgregoriancalendar.o qromancalendar.o qcryptographichash.o qdatetime.o qhash.o qlist.o qlocale.o qlocale_tools.o qmap.o qregexp.o qringbuffer.o qstringbuilder.o qstring.o qstringlist.o qversionnumber.o qvsnprintf.o qxmlstream.o qxmlutils.o qcore_unix.o qfilesystemengine_unix.o qfilesystemiterator_unix.o qfsfileengine_unix.o qlocale_unix.o qsettings_mac.o qcore_mac.o qoperatingsystemversion_darwin.o qcore_foundation.o qlibraryinfo.o -framework Foundation -framework CoreServices -framework ApplicationServices -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode-15.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk -mmacosx-version-min=10.13 -Wl,-dead_strip
Info: creating super cache file /private/tmp/qt_5.14-20240409-37517-lwyhj6/qt-everywhere-src-5.14.2/.qmake.super
Info: creating cache file /private/tmp/qt_5.14-20240409-37517-lwyhj6/qt-everywhere-src-5.14.2/.qmake.cache
Command line: -verbose -prefix /usr/local/Cellar/qt_5.14/5.14.2 -release -opensource -confirm-license -nomake examples -nomake tests -no-rpath -pkg-config -dbus-runtime -proprietary-codecs -system-freetype -system-libjpeg -system-libpng -system-pcre -system-zlib
Info: creating stash file /private/tmp/qt_5.14-20240409-37517-lwyhj6/qt-everywhere-src-5.14.2/.qmake.stash
Project ERROR: failed to parse default search paths from compiler output
```

qt 5.13 will download, but not build. Never seen that error before.

```
/Applications/Xcode-15.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -o "../bin/qmake" main.o meta.o option.o project.o property.o ioutils.o proitems.o qmakebuiltins.o qmakeevaluator.o qmakeglobals.o qmakeparser.o qmakevfs.o pbuilder_pbx.o makefile.o makefiledeps.o metamakefile.o projectgenerator.o unixmake2.o unixmake.o mingw_make.o msbuild_objectmodel.o msvc_nmake.o msvc_objectmodel.o msvc_vcproj.o msvc_vcxproj.o winmakefile.o xmloutput.o qutfcodec.o qendian.o qglobal.o qlogging.o qmalloc.o qnumeric.o qoperatingsystemversion.o qrandom.o qabstractfileengine.o qbuffer.o qdatastream.o qdebug.o qdir.o qdiriterator.o qfile.o qfiledevice.o qfileinfo.o qfilesystemengine.o qfilesystementry.o qfsfileengine.o qfsfileengine_iterator.o qiodevice.o qsettings.o qtemporaryfile.o qtextstream.o qjsonarray.o qjson.o qjsondocument.o qjsonobject.o qjsonparser.o qjsonvalue.o qmetatype.o qsystemerror.o qvariant.o quuid.o qarraydata.o qbitarray.o qbytearray.o qbytearraymatcher.o qcryptographichash.o qdatetime.o qhash.o qlinkedlist.o qlist.o qlocale.o qlocale_tools.o qmap.o qregexp.o qringbuffer.o qstringbuilder.o qstring_compat.o qstring.o qstringlist.o qversionnumber.o qvsnprintf.o qxmlstream.o qxmlutils.o qcore_unix.o qfilesystemengine_unix.o qfilesystemiterator_unix.o qfsfileengine_unix.o qlocale_unix.o qsettings_mac.o qcore_mac.o qoperatingsystemversion_darwin.o qcore_foundation.o qlibraryinfo.o -framework Foundation -framework CoreServices -framework ApplicationServices -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode-15.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk -mmacosx-version-min=10.12 -Wl,-dead_strip
Info: creating super cache file /private/tmp/qt_5.13-20240409-22664-yksk54/qt-everywhere-src-5.13.2/.qmake.super
Info: creating cache file /private/tmp/qt_5.13-20240409-22664-yksk54/qt-everywhere-src-5.13.2/.qmake.cache
Command line: -verbose -prefix /usr/local/Cellar/qt_5.13/5.13.2 -release -opensource -confirm-license -nomake examples -nomake tests -no-rpath -pkg-config -dbus-runtime -proprietary-codecs -system-freetype -system-libjpeg -system-libpng -system-pcre -system-zlib
Info: creating stash file /private/tmp/qt_5.13-20240409-22664-yksk54/qt-everywhere-src-5.13.2/.qmake.stash
Project ERROR: failed to parse default search paths from compiler output
```

qt 5.12.17 is 404, even on the ftp.osuosl.org site.

```
wget https://ftp.osuosl.org/pub/blfs/conglomeration/qt5/qt-everywhere-src-5.12.7.tar.xz
--2024-04-09 05:57:13--  https://ftp.osuosl.org/pub/blfs/conglomeration/qt5/qt-everywhere-src-5.12.7.tar.xz
Resolving ftp.osuosl.org (ftp.osuosl.org)... 64.50.233.100, 64.50.236.52, 140.211.166.134
Connecting to ftp.osuosl.org (ftp.osuosl.org)|64.50.233.100|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://ftp2.osuosl.org/pub/blfs/conglomeration/qt5/qt-everywhere-src-5.12.7.tar.xz [following]
--2024-04-09 05:57:13--  https://ftp2.osuosl.org/pub/blfs/conglomeration/qt5/qt-everywhere-src-5.12.7.tar.xz
Resolving ftp2.osuosl.org (ftp2.osuosl.org)... 140.211.166.134
Connecting to ftp2.osuosl.org (ftp2.osuosl.org)|140.211.166.134|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-04-09 05:57:13 ERROR 404: Not Found.
```

They have a 5.12.4, though. That seems like it'd be old enough to have concerning unpatched bugs, including security stuff? Don't think I want to use that.